# Generated by Django 3.2.12 on 2022-03-03 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='rates_count',
            new_name='rating_count',
        ),
    ]
