# Generated by Django 3.2.12 on 2022-03-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rename_rates_count_car_rating_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
