# Generated by Django 3.2.12 on 2022-03-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_auto_20220303_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='car',
            name='rating_sum',
            field=models.IntegerField(default=0),
        ),
    ]
